### ISSUE TITLE
No longer works with Python 3.7.2

### ISSUE THREAD

**Issue by Kaleidosium** [msikma/tune2tube#6]
If I run the script it gives me an Invalid Syntax error.
`Traceback (most recent call last):
  File "/Users/rifkik/Downloads/tune2tube-master/tune2tube.py", line 23, in <module>
    from t2t import tune2tube
  File "/Users/rifkik/Downloads/tune2tube-master/t2t/__init__.py", line 20, in <module>
    from tune2tube import Tune2Tube
  File "/Users/rifkik/Downloads/tune2tube-master/tune2tube.py", line 23, in <module>
    from t2t import tune2tube
  File "/Users/rifkik/Downloads/tune2tube-master/t2t/tune2tube.py", line 353
    except HttpError, e:
                    ^
SyntaxError: invalid syntax`
could you try to fix it?, I'm not this good with Python.

**Comment by haidvams** [comment]
same me , how to fix @IamRifki ?

**Comment by Kaleidosium** [comment]
I have no idea, this issue is super old anyways.

**Comment by Kaleidosium** [comment]
Closing as the project is dead.

**Comment by msikma** [comment]
Sorry for never responding to this. It's true, this doesn't work with Python 3. However, it's worse than that. The API functionality that this script uses isn't supported by Youtube anymore and although it still technically works, it incurs massive API rate limit costs so you're probably not able to upload more than one video at a time before your rate limit resets.

I'll update the readme sometime soon to reflect this.
